version: '3.5'

services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    image: postgres:14-alpine
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  honor:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      DISCORD_TOKEN: '${DISCORD_TOKEN}'
    volumes:
      - .:/app
volumes:
  pgdata:
